package com.crpi.fakeplayer.navigation.movement;

import com.crpi.fakeplayer.navigation.movement.controller.FakePlayerMovementController;
import com.crpi.fakeplayer.navigation.path.PathNode;
import com.crpi.fakeplayer.navigation.world.NavigationWorld;
import com.crpi.fakeplayer.fakeplayer.FakePlayerHandle;

/**
 * One atomic movement between two adjacent path nodes. Generated by a
 * {@link MovementProvider} during A*; executed by applying inputs through a
 * {@link FakePlayerMovementController} so Minecraft physics does the actual
 * movement.
 */
public interface Movement {
    /** Destination node (feet position). */
    PathNode target();

    /** Movement cost for A*. */
    double cost();

    /**
     * Applies inputs for this movement. Called every tick while this
     * movement is the current one.
     */
    void apply(FakePlayerHandle handle, FakePlayerMovementController controller, NavigationWorld world, long tick);

    /** Whether the player has reached the movement target. */
    boolean isComplete(FakePlayerHandle handle, NavigationWorld world);

    /** Describes the movement (for debug output). */
    String description();
}
